### ISSUE TITLE
代码复现过程出现raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)如何解决

### ISSUE THREAD

**Issue by Eyeistar** [Htring/BERT-BiLSTM-CRF_PL#2]

**Comment by Htring** [comment]
> 

这个问题让我有点突兀，没看出是在哪里报错的

**Comment by Eyeistar** [comment]
没事啦，都解决啦。谢谢您的回复。祝您生活愉快。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Htring/BERT-BiLSTM-CRF_PL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月24日(星期六) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Htring/BERT-BiLSTM-CRF_PL] 代码复现过程出现raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)如何解决 (Issue #2)





   
这个问题让我有点突兀，没看出是在哪里报错的
