### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by 17478020** [Htring/BERT-BiLSTM-CRF_PL#3]
您好，我想问下这个文件不是自动生成的吗？
![image](https://user-images.githubusercontent.com/63388342/191647433-28b6a7bd-c404-4a61-89fc-184dd1a4c2b7.png)

**Comment by Htring** [comment]
是的，这个文件在是训练时自动生成的。trainer.py当前处于模型使用模式。

**Comment by Htring** [comment]
> 您好，我想问下这个文件不是自动生成的吗？ ![image](https://user-images.githubusercontent.com/63388342/191647433-28b6a7bd-c404-4a61-89fc-184dd1a4c2b7.png)

是的，这个文件在是训练时自动生成的。trainer.py当前处于模型使用模式。
